services:
  react:
    build:
      context: ../frontend/
      target: development
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3000
    ports:
      - "${FRONTEND_PORT:-3001}:3001"
    networks:
      - ci-cd-kube

networks:
  ci-cd-kube:
    driver: bridge
